name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
      - name: Normalize
        run: |
          python tools/normalize.py
      - name: Validate
        run: |
          python tools/validate.py
      - name: Counts & Unique
        run: |
          python tools/counts.py
      - name: Build packs
        run: |
          python tools/build_packs.py
      - name: Dedupe tree
        run: |
          python tools/dedupe.py
      - name: Manifest YAML
        run: |
          python tools/manifest_yaml.py
      - name: Frequency metadata (stub)
        run: |
          python tools/frequency_stub.py


